[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@fhevm/solidity/=lib/fhevm-solidity/",
    "encrypted-types/=lib/encrypted-types/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/confidential-contracts/=lib/openzeppelin-confidential-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
